name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '19 3 31 * *'

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pytest
